version: '3.9'
services:
#  word-of-god:
#    container_name: word-of-god
#    #    image: madouma2/word-of-god:latest
#    ports:
#      - "80:80"

  wordofgodui:
    container_name: wordofgodui
    build: .
    tty: true
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - internal


networks:
  internal:
    external: true